export const countrys=["India","Nepal","Bangladesh","srilanka","America","Canada","singapure"];
export const states=["Karnatak","Telangana","Tamilnadu","Maharastra","Andrapradesh","Utterpradesh","Delhi"]
export const city=["Bengaluru","Andra","Channai","Mumbai","Hydrabad","Noida","Delhi ncr"];
export const areas=["HSR Layout","mohmad","venkai","shivaji nagar","bande","charminar","nrc new"];
export const products=["SnaxVending","Itvending","Stationary Vending","Station vending"];
export const companys =["Diageo","BOSCH","Simplilearn","Infosys","Wipro","HCL"];
export const clients=["Sisco","Genpact","ZoHo","Snaxsmart","techmahindra"];
export const Admins=["Super","Account","Support","SuperAdmin","Manager","CEO"]
export const Refiller=["Dinesh","Manoj","Kartik","Shubham","Sharan","Anil"];
export const Refillers=["Avinash","Mahesh","Swami","Hemanth","Kiran","Kumar"];
export const warehouse=["HSR","Manyata","Jayanagar","Rajaji nagar",]